# Generated by Django 5.0.2 on 2024-02-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_categoria_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
