# Generated by Django 5.0.2 on 2024-02-19 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_categoria_orden'),
        ('menu', '0003_alter_plato_precio'),
    ]

    operations = [
    ]
